development:
  adapter: postgresql
  encoding: unicode
  database: answers_dev
  username: answers
  password: answers
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: answers_test
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: answers_production
  host: localhost
  pool: 5
  timeout: 5000
